win = turtle.Screen()
win.bgcolor("light sky blue")

sepalTurtle = turtle.Turtle()
sepalTurtle.speed(0)
sepalTurtle.color("dark green", "spring green")
sepalTurtle.hideturtle()

petalTurtle = turtle.Turtle()
petalTurtle.speed(0)
petalTurtle.color('dark red', 'light coral')
petalTurtle.hideturtle()

centerTurtle = turtle.Turtle()
centerTurtle.speed(0)
centerTurtle.color('purple4')
centerTurtle.hideturtle()

stampTurtle = turtle.Turtle()
stampTurtle.color("gold")
stampTurtle.speed(0)
stampTurtle.shape("turtle")
stampTurtle.hideturtle()

sepalTurtle.up()                    # TODO: Step 2: start here
sepalTurtle.goto(0, 0)
sepalTurtle.down()
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)

petalTurtle.up()
petalTurtle.goto(0, 0)
petalTurtle.down()
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)

centerTurtle.up()
centerTurtle.goto(0, -15)
centerTurtle.down()
centerTurtle.begin_fill()
centerTurtle.circle(15)
centerTurtle.end_fill()

stampTurtle.up()
stampTurtle.goto(-2,0)
stampTurtle.down()
stampTurtle.stamp()

sepalTurtle.up()
sepalTurtle.goto(0, 220)
sepalTurtle.down()
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)

petalTurtle.up()
petalTurtle.goto(0, 220)
petalTurtle.down()
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)

centerTurtle.up()
centerTurtle.goto(0, 205)
centerTurtle.down()
centerTurtle.begin_fill()
centerTurtle.circle(15)
centerTurtle.end_fill()

stampTurtle.up()
stampTurtle.goto(-2,220)
stampTurtle.down()
stampTurtle.stamp()

sepalTurtle.up()
sepalTurtle.goto(220, 0)
sepalTurtle.down()
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)

petalTurtle.up()
petalTurtle.goto(220, 0)
petalTurtle.down()
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)

centerTurtle.up()
centerTurtle.goto(220, -15)
centerTurtle.down()
centerTurtle.begin_fill()
centerTurtle.circle(15)
centerTurtle.end_fill()

stampTurtle.up()
stampTurtle.goto(218,0)
stampTurtle.down()
stampTurtle.stamp()

sepalTurtle.up()
sepalTurtle.goto(0, -220)
sepalTurtle.down()
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)

petalTurtle.up()
petalTurtle.goto(0, -220)
petalTurtle.down()
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)

centerTurtle.up()
centerTurtle.goto(0, -235)
centerTurtle.down()
centerTurtle.begin_fill()
centerTurtle.circle(15)
centerTurtle.end_fill()

stampTurtle.up()
stampTurtle.goto(-2,-220)
stampTurtle.down()
stampTurtle.stamp()

sepalTurtle.up()
sepalTurtle.goto(-220, 0)
sepalTurtle.down()
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)
sepalTurtle.begin_fill()
sepalTurtle.circle(50)
sepalTurtle.end_fill()
sepalTurtle.left(72)

petalTurtle.up()
petalTurtle.goto(-220, 0)
petalTurtle.down()
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)
petalTurtle.begin_fill()
petalTurtle.circle(25)
petalTurtle.end_fill()
petalTurtle.left(72)

centerTurtle.up()
centerTurtle.goto(-220, -15)
centerTurtle.down()
centerTurtle.begin_fill()
centerTurtle.circle(15)
centerTurtle.end_fill()

stampTurtle.up()
stampTurtle.goto(-222,0)
stampTurtle.down()
stampTurtle.stamp()

win.exitonclick()

#This program uses the turtle graphics library to draw five flowers on the screen.
#The flowers are arranged in a cross pattern: one in the center, and one each
#to the top, bottom, left, and right of the center.

#Each flower is composed of several layers, drawn in this order:
#1. Five large green circles form the sepals (the leafy part).
#2. Five smaller red/coral circles form the petals.
#3. One small purple circle forms the center of the flower.
#4. A yellow turtle shape is stamped in the middle, like a honeybee.

#The program uses four separate turtle objects to perform the drawing:
#- sepalTurtle: Draws the green sepals.
#- petalTurtle: Draws the red petals.
#- centerTurtle: Draws the purple center.
#- stampTurtle: Stamps the yellow "bee".
"""

# The rest of your original code goes here...
# I will omit it for brevity, just add the comment above to your file.
# Make sure to run the code to see what it does.

win = turtle.Screen()
win.bgcolor("light sky blue")

#sepalTurtle = turtle.Turtle()
